#![forbid(unsafe_code)]
//! Shared plain types for the replay-renderer workspace (ARCHITECTURE §1).
//!
//! Plain data only: no I/O, no tokio, no tonic.

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ReplayMode {
    VerifyOnly,
    RenderVideo,
}

/// snapshot-store caller-assigned node id, unique within an experiment
/// (snapshot-store tree API; ARCHITECTURE §1).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct NodeId(pub u64);

/// Scopes every tree lookup (snapshot-store tree API; ARCHITECTURE §1).
#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ExperimentId(pub String);

/// BLAKE3-256 manifest hash (snapshot-store contract; ARCHITECTURE §1).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SnapshotRef(pub [u8; 32]);

/// The hypervisor's CHAINED state hash (determinism-hypervisor
/// ARCHITECTURE §8.5). Never a flat whole-memory digest.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct StateHash(pub [u8; 32]);

/// Instruction count, SEGMENT-RELATIVE: DHILOG icounts restart at 0 per
/// segment; there is no global icount (hypervisor API.md §3.4 rule 3).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
pub struct Icount(pub u64);

/// ULID, generated by replayd (ARCHITECTURE §1).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct JobId(pub [u8; 16]);

/// The hypervisor host's determinism-class tuple (hypervisor API.md §2.8);
/// published in `.dilog` META and artifact metadata — re-verification
/// hard-requires a class-matching host.
#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct DeterminismClass {
    pub cpu_model: String,
    pub microcode: String,
    pub host_kernel: String,
    pub vmm_version: String,
}

/// Guest framebuffer geometry. Not invented here — read from
/// reference-workload's guest manifest via tree-root attrs (ARCHITECTURE §1).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct FramebufferDesc {
    pub gpa_base: u64,
    pub width: u16,
    pub height: u16,
    pub stride_bytes: u32,
    pub pixel_format: PixelFormat,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PixelFormat {
    Rgb555Le,
    Bgr555Le,
    Rgb565Le,
    Indexed8 { palette_gpa: u64 },
}
