//! M3 encode tests (IMPLEMENTATION-PLAN §M3; plan package 04 §3).
//!
//! Frame source for the MP4 tests: the fixture pack
//! `tests/fixtures/frames.rfp` (600 lz4-compressed native RGB555LE 256×224
//! frames). The demo fps `6010/100` is a TEST parameter from the workload
//! manifest — never read from the `.rfp` header clock fields (those carry
//! the DHILOG vns clock).

use std::path::{Path, PathBuf};

use replay_encode::args::{
    check_gif_range, decode_to_rawvideo_args, gif_encode_args, gif_palettegen_args, mp4_args,
    webp_args, Codec, EncoderChoice, Geometry, VideoOptions, GIF_DEFAULT_MAX_FRAMES,
};
use replay_encode::probe::probe_encoders;
use replay_encode::session::{run_capture_stdout, run_with_frames, EncoderSession};
use replay_encode::stills::{contact_sheet, thumb_strip};
use replay_encode::EncodeError;
use replay_frames::codec::decompress_frame;
use replay_frames::rfp::{read_rfp, Comp, RfpReadOutcome};
use replay_frames::{pad_to_even, scale_nn, Lut, Rgb24Frame};

const FPS_NUM: u32 = 6010;
const FPS_DEN: u32 = 100;

fn video_options(crf: u32) -> VideoOptions {
    VideoOptions {
        codec: Codec::H264,
        target_width: 1920,
        target_height: 1080,
        force_software: true,
        par_correct: false,
        crf_or_cq: crf,
    }
}

fn geometry(w: u32, h: u32) -> Geometry {
    Geometry {
        out_w: w,
        out_h: h,
        fps_num: FPS_NUM,
        fps_den: FPS_DEN,
    }
}

// ---- temp output dirs -------------------------------------------------

struct TestDir(PathBuf);

impl TestDir {
    fn new(test_name: &str) -> Self {
        let dir = std::env::temp_dir()
            .join(format!("replay-encode-tests-{}", std::process::id()))
            .join(test_name);
        std::fs::create_dir_all(&dir).expect("create test temp dir");
        TestDir(dir)
    }

    fn path(&self, name: &str) -> String {
        self.0.join(name).to_str().expect("utf-8 path").to_string()
    }
}

impl Drop for TestDir {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

// ---- fixture loading ---------------------------------------------------

fn fixture_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/fixtures/frames.rfp")
}

/// Load the fixture pack and return the native-size RGB24 frames in
/// record order. Panics with a clear message when the pack is absent
/// (it is generated by `cargo xtask regen-fixtures` and exists in CI).
fn load_fixture_rgb24(limit: usize) -> Vec<Rgb24Frame> {
    let path = fixture_path();
    let bytes = std::fs::read(&path).unwrap_or_else(|e| {
        panic!(
            "fixture pack {} is required for this test but could not be read \
             (generate it with `cargo xtask regen-fixtures`): {e}",
            path.display()
        )
    });
    let (header, records) = match read_rfp(&bytes).expect("frames.rfp parses") {
        RfpReadOutcome::Complete { header, records } => (header, records),
        RfpReadOutcome::Torn { .. } => panic!("frames.rfp fixture is torn — regenerate it"),
    };
    let desc = header.desc;
    let lut = Lut::for_format(desc.pixel_format).expect("fixture pixel format has a LUT");
    let native_len = desc.stride_bytes as usize * desc.height as usize;
    records
        .iter()
        .take(limit)
        .map(|r| {
            let raw = match r.comp {
                Comp::Raw => r.bytes.clone(),
                Comp::Lz4 => decompress_frame(&r.bytes, native_len)
                    .expect("fixture frame decompresses to stride*height bytes"),
            };
            lut.convert(&raw, &desc).expect("fixture frame converts")
        })
        .collect()
}

// ---- synthetic pixel-art frames (for GIF/WebP/stills tests) -----------

/// Blocky, low-palette frames — pixel-art-like (noise encodes badly and
/// dithers badly; these must be palette-friendly).
fn synthetic_frame(i: usize, w: u32, h: u32) -> Rgb24Frame {
    const PALETTE: [[u8; 3]; 8] = [
        [0, 0, 0],
        [255, 255, 255],
        [224, 48, 48],
        [48, 224, 48],
        [48, 48, 224],
        [224, 224, 48],
        [48, 224, 224],
        [160, 96, 32],
    ];
    let mut pixels = Vec::with_capacity(3 * w as usize * h as usize);
    for y in 0..h {
        for x in 0..w {
            let c = PALETTE[((x / 16 + y / 16) as usize + i) % PALETTE.len()];
            pixels.extend_from_slice(&c);
        }
    }
    Rgb24Frame {
        width: w,
        height: h,
        pixels,
    }
}

// ---- args unit tests ---------------------------------------------------

#[test]
fn mp4_args_use_rational_fps_yuv420p_faststart() {
    let o = video_options(18);
    let g = geometry(1024, 896);
    let args = mp4_args(
        &o,
        &g,
        EncoderChoice::Libx264,
        "determinism:test:00",
        "out.mp4",
    );
    // The exact rational string — never a float (§7.2: long videos drift).
    assert!(args.iter().any(|a| a == "6010/100"), "args: {args:?}");
    assert!(
        !args.iter().any(|a| a.contains("60.1")),
        "float fps leaked: {args:?}"
    );
    assert!(args.iter().any(|a| a == "yuv420p"));
    assert!(args.iter().any(|a| a == "+faststart"));
    assert!(args.iter().any(|a| a == "comment=determinism:test:00"));
    assert!(args.iter().any(|a| a == "libx264"));
    assert!(args.contains(&"veryslow".to_string()));
    assert!(!args.contains(&"-aspect".to_string()));

    // par_correct only adds the container aspect hint.
    let par = VideoOptions {
        par_correct: true,
        ..o
    };
    let args = mp4_args(&par, &g, EncoderChoice::Libx264, "c", "out.mp4");
    let pos = args
        .iter()
        .position(|a| a == "-aspect")
        .expect("-aspect present");
    assert_eq!(args[pos + 1], "4:3");
}

#[test]
fn mp4_args_default_quality_per_encoder() {
    let o = video_options(0); // 0 ⇒ encoder default
    let g = geometry(1024, 896);
    let x264 = mp4_args(&o, &g, EncoderChoice::Libx264, "c", "o.mp4");
    let crf = x264.iter().position(|a| a == "-crf").unwrap();
    assert_eq!(x264[crf + 1], "18");
    let x265 = mp4_args(&o, &g, EncoderChoice::Libx265, "c", "o.mp4");
    let crf = x265.iter().position(|a| a == "-crf").unwrap();
    assert_eq!(x265[crf + 1], "20");
    let nvenc = mp4_args(&o, &g, EncoderChoice::H264Nvenc, "c", "o.mp4");
    let cq = nvenc.iter().position(|a| a == "-cq").unwrap();
    assert_eq!(nvenc[cq + 1], "19");
    assert!(nvenc.iter().any(|a| a == "h264_nvenc"));
}

// ---- MP4 contract ------------------------------------------------------

#[tokio::test]
async fn mp4_ffprobe_contract() {
    let dir = TestDir::new("mp4_ffprobe_contract");
    let out = dir.path("contract.mp4");

    let table = probe_encoders("ffmpeg", true).await; // force_software
    assert_eq!(table.h264, EncoderChoice::Libx264);

    let o = video_options(18);
    let g = geometry(1024, 896);
    let args = mp4_args(&o, &g, table.h264, "determinism:test-job:deadbeef", &out);
    let mut session = EncoderSession::spawn("ffmpeg", &args)
        .await
        .expect("spawn ffmpeg");
    for native in load_fixture_rgb24(usize::MAX) {
        let up = pad_to_even(&scale_nn(&native, 4));
        assert_eq!((up.width, up.height), (1024, 896));
        session.write_frame(&up.pixels).await.expect("write frame");
    }
    session.finish().await.expect("ffmpeg finishes cleanly");

    let probe = tokio::process::Command::new("ffprobe")
        .args([
            "-v",
            "error",
            "-select_streams",
            "v:0",
            "-show_entries",
            "stream=codec_name,width,height,r_frame_rate,nb_frames",
            "-of",
            "json",
            &out,
        ])
        .output()
        .await
        .expect("run ffprobe");
    assert!(
        probe.status.success(),
        "ffprobe failed: {}",
        String::from_utf8_lossy(&probe.stderr)
    );
    let v: serde_json::Value = serde_json::from_slice(&probe.stdout).expect("ffprobe json");
    let s = &v["streams"][0];
    assert_eq!(s["codec_name"], "h264");
    assert_eq!(s["width"], 1024);
    assert_eq!(s["height"], 896);
    assert_eq!(s["nb_frames"], "600");
    // 6010/100 reduced by ffmpeg.
    assert_eq!(s["r_frame_rate"], "601/10");
}

#[tokio::test]
async fn mp4_decode_back_mean_abs_error_below_3() {
    let dir = TestDir::new("mp4_decode_back");
    let out = dir.path("mae.mp4");

    // 120-frame subset at ×2 keeps runtime and memory sane; NEVER
    // golden-compare encoded bitstreams (encoder builds differ).
    let frames: Vec<Rgb24Frame> = load_fixture_rgb24(120)
        .iter()
        .map(|f| pad_to_even(&scale_nn(f, 2)))
        .collect();
    let (w, h) = (frames[0].width, frames[0].height);

    let o = video_options(18);
    let g = geometry(w, h);
    let args = mp4_args(&o, &g, EncoderChoice::Libx264, "determinism:test:mae", &out);
    run_with_frames("ffmpeg", &args, frames.iter().map(|f| f.pixels.as_slice()))
        .await
        .expect("encode");

    let decoded = run_capture_stdout("ffmpeg", &decode_to_rawvideo_args(&out, w, h), &[])
        .await
        .expect("decode back");
    let frame_bytes = 3 * w as usize * h as usize;
    assert_eq!(
        decoded.len(),
        frame_bytes * frames.len(),
        "decoded frame count/size"
    );

    let mut sum: u64 = 0;
    for (i, frame) in frames.iter().enumerate() {
        let d = &decoded[i * frame_bytes..(i + 1) * frame_bytes];
        for (a, b) in frame.pixels.iter().zip(d) {
            sum += u64::from(a.abs_diff(*b));
        }
    }
    let mae = sum as f64 / (frame_bytes * frames.len()) as f64;
    assert!(mae < 3.0, "mean absolute error {mae} >= 3.0");
}

// ---- probe --------------------------------------------------------------

#[tokio::test]
async fn probe_falls_back_to_libx264_without_gpu() {
    // Guard: ffmpeg must actually be resolvable — a missing binary would
    // also yield the software table and make this test vacuous.
    let version = tokio::process::Command::new("ffmpeg")
        .arg("-version")
        .output()
        .await
        .expect("ffmpeg resolvable in PATH");
    assert!(version.status.success());

    let table = probe_encoders("ffmpeg", false).await;
    assert_eq!(table.h264, EncoderChoice::Libx264);
    assert_eq!(table.hevc, EncoderChoice::Libx265);
}

#[tokio::test]
#[ignore = "hardware: spark-nvenc"]
async fn probe_selects_nvenc_on_spark() {
    let table = probe_encoders("ffmpeg", false).await;
    assert_eq!(table.h264, EncoderChoice::H264Nvenc);
    assert_eq!(table.hevc, EncoderChoice::HevcNvenc);
}

// ---- GIF ----------------------------------------------------------------

#[tokio::test]
async fn gif_respects_max_frames_and_dither_none() {
    // dither=none is normative (§7.4).
    let g = geometry(256, 224);
    let args = gif_encode_args(&g, "palette.png", "out.gif");
    assert!(
        args.iter().any(|a| a.contains("paletteuse=dither=none")),
        "args: {args:?}"
    );

    // Range limit: > max refused with a typed error.
    assert!(check_gif_range(900, GIF_DEFAULT_MAX_FRAMES).is_ok());
    match check_gif_range(901, GIF_DEFAULT_MAX_FRAMES) {
        Err(EncodeError::GifRangeExceeded {
            frame_count: 901,
            max_frames: 900,
        }) => {}
        other => panic!("expected GifRangeExceeded, got {other:?}"),
    }

    // Two-pass encode of a small GIF actually works.
    let dir = TestDir::new("gif_two_pass");
    let palette = dir.path("palette.png");
    let out = dir.path("out.gif");
    let frames: Vec<Rgb24Frame> = (0..60).map(|i| synthetic_frame(i, 256, 224)).collect();
    run_with_frames(
        "ffmpeg",
        &gif_palettegen_args(&g, &palette),
        frames.iter().map(|f| f.pixels.as_slice()),
    )
    .await
    .expect("palettegen pass");
    run_with_frames(
        "ffmpeg",
        &gif_encode_args(&g, &palette, &out),
        frames.iter().map(|f| f.pixels.as_slice()),
    )
    .await
    .expect("gif encode pass");
    let meta = std::fs::metadata(&out).expect("gif exists");
    assert!(meta.len() > 0, "gif is empty");
}

// ---- WebP ----------------------------------------------------------------

#[tokio::test]
async fn webp_lossless_round_trips_byte_identical() {
    let dir = TestDir::new("webp_lossless");
    let out = dir.path("out.webp");
    let (w, h) = (256, 224);
    let g = geometry(w, h);
    let frames: Vec<Rgb24Frame> = (0..30).map(|i| synthetic_frame(i, w, h)).collect();

    run_with_frames(
        "ffmpeg",
        &webp_args(&g, &out),
        frames.iter().map(|f| f.pixels.as_slice()),
    )
    .await
    .expect("webp encode");

    // Decode back via ffmpeg. ffmpeg's native webp decoder cannot demux
    // animated WebP (it skips ANIM/ANMF chunks — a long-standing gap), so
    // split the container: each ANMF frame's lossless VP8L payload is
    // rewrapped as a static WebP, which ffmpeg decodes exactly. Lossless
    // means byte-identical RGB.
    let container = std::fs::read(&out).expect("webp exists");
    let stills = split_animated_webp(&container, w, h);
    assert_eq!(stills.len(), frames.len(), "ANMF frame count");
    let frame_bytes = 3 * w as usize * h as usize;
    for (i, (still, src)) in stills.iter().zip(&frames).enumerate() {
        let still_path = dir.path(&format!("frame_{i}.webp"));
        std::fs::write(&still_path, still).expect("write still webp");
        let decoded =
            run_capture_stdout("ffmpeg", &decode_to_rawvideo_args(&still_path, w, h), &[])
                .await
                .expect("decode still webp frame");
        assert_eq!(decoded.len(), frame_bytes, "decoded frame {i} size");
        assert_eq!(
            decoded, src.pixels,
            "webp lossless frame {i} is not byte-identical"
        );
    }
}

/// Split an animated WebP into per-frame static WebP files (VP8L payloads
/// rewrapped in a minimal RIFF container). Asserts every ANMF frame is a
/// full-canvas lossless frame so the comparison is well-defined.
fn split_animated_webp(webp: &[u8], canvas_w: u32, canvas_h: u32) -> Vec<Vec<u8>> {
    let le24 = |b: &[u8]| u32::from(b[0]) | u32::from(b[1]) << 8 | u32::from(b[2]) << 16;
    assert_eq!(&webp[0..4], b"RIFF", "not a RIFF file");
    assert_eq!(&webp[8..12], b"WEBP", "not a WebP file");
    let mut stills = Vec::new();
    let mut off = 12;
    while off + 8 <= webp.len() {
        let fourcc = &webp[off..off + 4];
        let size = u32::from_le_bytes(webp[off + 4..off + 8].try_into().unwrap()) as usize;
        let payload = &webp[off + 8..off + 8 + size];
        if fourcc == b"ANMF" {
            // 16-byte ANMF header: x/2, y/2, w-1, h-1 (24-bit LE each),
            // duration, flags — then the frame subchunk.
            assert_eq!(le24(&payload[0..3]), 0, "frame x offset");
            assert_eq!(le24(&payload[3..6]), 0, "frame y offset");
            assert_eq!(le24(&payload[6..9]) + 1, canvas_w, "frame width");
            assert_eq!(le24(&payload[9..12]) + 1, canvas_h, "frame height");
            let sub = &payload[16..];
            assert_eq!(&sub[0..4], b"VP8L", "expected a lossless frame chunk");
            let vp8l_len = u32::from_le_bytes(sub[4..8].try_into().unwrap()) as usize;
            let vp8l = &sub[8..8 + vp8l_len];

            let mut still = Vec::with_capacity(20 + vp8l.len() + 1);
            still.extend_from_slice(b"RIFF");
            let chunk_len = 8 + vp8l.len() + (vp8l.len() & 1);
            still.extend_from_slice(&((4 + chunk_len) as u32).to_le_bytes());
            still.extend_from_slice(b"WEBP");
            still.extend_from_slice(b"VP8L");
            still.extend_from_slice(&(vp8l_len as u32).to_le_bytes());
            still.extend_from_slice(vp8l);
            if vp8l.len() & 1 == 1 {
                still.push(0);
            }
            stills.push(still);
        }
        off += 8 + size + (size & 1);
    }
    stills
}

// ---- stills determinism ---------------------------------------------------

#[test]
fn stills_are_deterministic() {
    let frames: Vec<Rgb24Frame> = (0..37).map(|i| synthetic_frame(i, 64, 56)).collect();
    let pairs: Vec<(u64, &Rgb24Frame)> = frames
        .iter()
        .enumerate()
        .map(|(i, f)| (i as u64 * 3, f))
        .collect();

    let sheet_a = contact_sheet(&pairs);
    let sheet_b = contact_sheet(&pairs);
    assert!(sheet_a.width > 0 && sheet_a.height > 0);
    assert_eq!(sheet_a, sheet_b, "contact_sheet is not deterministic");

    let strip_a = thumb_strip(&pairs);
    let strip_b = thumb_strip(&pairs);
    assert!(strip_a.width > 0 && strip_a.height > 0);
    assert_eq!(strip_a, strip_b, "thumb_strip is not deterministic");
}
