#![forbid(unsafe_code)]
//! Workspace task runner. Currently one subcommand:
//!
//! `cargo xtask regen-fixtures [--check]`
//!
//! Regenerates every committed fixture this repo knows about, as a pure
//! function of the seeds hard-coded in [`fixtures`]. `--check` regenerates
//! to memory and byte-compares against the committed tree (CI's single
//! freshness gate) — exit nonzero on any diff. Fixtures are never
//! hand-edited.

mod fixtures;

use std::path::{Path, PathBuf};
use std::process::ExitCode;

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    match args.first().map(String::as_str) {
        Some("regen-fixtures") => {
            let check = args.iter().any(|a| a == "--check");
            regen_fixtures(check)
        }
        _ => {
            eprintln!("usage: cargo xtask regen-fixtures [--check]");
            ExitCode::from(2)
        }
    }
}

fn repo_root() -> PathBuf {
    // xtask always lives at <root>/xtask.
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask has a parent dir")
        .to_path_buf()
}

fn regen_fixtures(check: bool) -> ExitCode {
    let root = repo_root();
    let generated = fixtures::generate();

    if check {
        let mut bad = 0usize;
        for (rel, bytes) in &generated {
            let path = root.join(rel);
            match std::fs::read(&path) {
                Ok(on_disk) if &on_disk == bytes => {}
                Ok(_) => {
                    eprintln!("STALE: {rel} differs from regenerated bytes");
                    bad += 1;
                }
                Err(e) => {
                    eprintln!("MISSING: {rel}: {e}");
                    bad += 1;
                }
            }
        }
        // Unknown files under the fixture roots are also a failure: --check
        // is the single freshness gate for the whole committed set.
        let known: std::collections::BTreeSet<&str> =
            generated.iter().map(|(rel, _)| rel.as_str()).collect();
        for rel in walk_files(&root, "tests/fixtures") {
            if !known.contains(rel.as_str()) {
                eprintln!("UNKNOWN: {rel} is not produced by regen-fixtures");
                bad += 1;
            }
        }
        if bad > 0 {
            eprintln!("regen-fixtures --check: {bad} problem(s)");
            return ExitCode::FAILURE;
        }
        println!("regen-fixtures --check: {} files clean", generated.len());
        ExitCode::SUCCESS
    } else {
        for (rel, bytes) in &generated {
            let path = root.join(rel);
            std::fs::create_dir_all(path.parent().unwrap()).expect("mkdir fixture dir");
            std::fs::write(&path, bytes).expect("write fixture");
        }
        println!("regen-fixtures: wrote {} files", generated.len());
        ExitCode::SUCCESS
    }
}

fn walk_files(root: &Path, rel_dir: &str) -> Vec<String> {
    let mut out = Vec::new();
    let dir = root.join(rel_dir);
    let Ok(entries) = std::fs::read_dir(&dir) else {
        return out;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let rel = format!("{rel_dir}/{}", entry.file_name().to_string_lossy());
        if path.is_dir() {
            out.extend(walk_files(root, &rel));
        } else {
            out.push(rel);
        }
    }
    out
}
